kind: Pod
apiVersion: v1
metadata:
  name: intra
spec:
  containers:
    - image: docker.io/lavies/intramage:v1
      name: intra
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP